name: Metrics

on:
  schedule:
    - cron: "0 0 * * *" # every day (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  achievements:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          filename: achievements.svg
          token: ${{ secrets.METRICS_SECRET }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: anittavargh
          base: ""
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: no
          plugin_achievements_display: compact
          plugin_achievements_limit: 0
          plugin_achievements_ignored: manager
          debug: yes
          debug_flags: achievements

  header:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: header.svg
          token: ${{ secrets.METRICS_SECRET }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: anittavargh
          template: classic
          base: header
          config_timezone: ${{ secrets.USER_TIMEZONE }}

  lines:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: lines-of-code.svg
          token: ${{ secrets.METRICS_SECRET }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: anittavargh
          base: ""
          plugin_lines: yes

  activity_community:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: acti_comm.svg
          token: ${{ secrets.METRICS_SECRET }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: anittavargh
          template: classic
          base: activity, community
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          config_display: compact
          config_padding: 0, 8%

  iso_calendar:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: iso_calender.svg
          token: ${{ secrets.METRICS_SECRET }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: anittavargh
          template: classic
          base: ""
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

  habits:
    needs: repositories
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-habits.svg
          token: ${{ secrets.METRICS_SECRET }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: anittavargh
          template: classic
          base: ""
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          plugin_habits: yes
          plugin_habits_from: 300
          plugin_habits_days: 14
          plugin_habits_charts: yes
          plugin_habits_trim: yes
          plugin_habits_facts: yes

  issue_pr_lang:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: issue_pr_lang.svg
          token: ${{ secrets.METRICS_SECRET }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: anittavargh
          template: classic
          base: ""
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          plugin_followup: yes
          plugin_languages: yes
          plugin_languages_limit: 12
          plugin_languages_sections: most-used

  repositories:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: repositories.svg
          token: ${{ secrets.METRICS_SECRET }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: anittavargh
          template: classic
          base: repositories
          config_timezone: ${{ secrets.USER_TIMEZONE }}
