name: Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Header / Overview
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: anittavarghese
          template: classic
          filename: header.svg
          base: header, activity, community

      - name: Streak
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: anittavarghese
          template: classic
          filename: streak.svg
          base: ""
          plugin_streak: yes

      - name: Languages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: anittavarghese
          template: classic
          filename: languages.svg
          base: ""
          plugin_languages: yes
          plugin_languages_limit: 8

      - name: Habits
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: anittavarghese
          template: classic
          filename: habits.svg
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes

      - name: Isometric calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: anittavarghese
          template: classic
          filename: iso_calendar.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
